-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 13:07:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api-restful-shop-diagram-db
-- -----------------------------------------------------
-- Diagrams:
-- Users
-- UsersDetails
-- Adress
-- Telephones
-- TypeDocument
-- Products
-- Sales
-- Cobros
-- Tickets

-- -----------------------------------------------------
-- Schema api-restful-shop-diagram-db
--
-- Diagrams:
-- Users
-- UsersDetails
-- Adress
-- Telephones
-- TypeDocument
-- Products
-- Sales
-- Cobros
-- Tickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api-restful-shop-diagram-db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `api-restful-shop-diagram-db` ;

-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Address` (
  `idaddress` INT NOT NULL,
  `address_line1` VARCHAR(40) NOT NULL,
  `address_line2` VARCHAR(40) NULL,
  `city` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `UsersDetails_idusersdetails` INT NOT NULL,
  PRIMARY KEY (`idaddress`));

CREATE INDEX `fk_Adress_UsersDetails1_idx` ON `api-restful-shop-diagram-db`.`Address` (`UsersDetails_idusersdetails` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Categorys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Categorys` (
  `category_id` INT NOT NULL,
  `nameCategoria` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Cobros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Cobros` (
  `idcobros`  NOT NULL,
  `abono` DOUBLE NOT NULL,
  `saldo_historico` DOUBLE NULL,
  `date_abono` DATETIME NOT NULL,
  `UsersDetails_idusersdetails` INT NOT NULL,
  `Sales_idsales` INT NOT NULL,
  PRIMARY KEY (`idcobros`));

CREATE INDEX `fk_Cobros_UsersDetails1_idx` ON `api-restful-shop-diagram-db`.`Cobros` (`UsersDetails_idusersdetails` ASC);

CREATE INDEX `fk_Cobros_Sales1_idx` ON `api-restful-shop-diagram-db`.`Cobros` (`Sales_idsales` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Products` (
  `idproducts` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT(255) NULL,
  `price` DOUBLE NULL,
  `cost` DOUBLE NULL,
  `stock` INT(10000) NULL,
  `imgURL` TEXT NULL,
  `Categorys_category_id` INT NOT NULL,
  PRIMARY KEY (`idproducts`, `Categorys_category_id`));

CREATE INDEX `fk_Products_Categorys1_idx` ON `api-restful-shop-diagram-db`.`Products` (`Categorys_category_id` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Sales` (
  `idsales` INT NOT NULL,
  `num_sale` INT NOT NULL,
  `date_sale` DATETIME NOT NULL,
  `intervalos_cuotas` DATETIME NOT NULL,
  `abono_inicial` DOUBLE NOT NULL,
  `cant_cuotas` TINYINT NOT NULL,
  `Tickets_idtickets`  NOT NULL,
  `UsersDetails_idusersdetails` INT NOT NULL,
  PRIMARY KEY (`idsales`, `UsersDetails_idusersdetails`));

CREATE INDEX `fk_Sales_Tickets1_idx` ON `api-restful-shop-diagram-db`.`Sales` (`Tickets_idtickets` ASC);

CREATE INDEX `fk_Sales_UsersDetails1_idx` ON `api-restful-shop-diagram-db`.`Sales` (`UsersDetails_idusersdetails` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Telephones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Telephones` (
  `idtelephone` INT NOT NULL,
  `Telephone` TINYINT(13) NOT NULL,
  `UsersDetails_idusersdetails` INT NOT NULL,
  PRIMARY KEY (`idtelephone`));

CREATE INDEX `fk_Telephones_UsersDetails1_idx` ON `api-restful-shop-diagram-db`.`Telephones` (`UsersDetails_idusersdetails` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Tickets` (
  `idtickets`  NOT NULL,
  `cant_products` INT NULL,
  `total_venta` DOUBLE NULL,
  `Products_idproducts` INT NOT NULL,
  PRIMARY KEY (`idtickets`));

CREATE INDEX `fk_Tickets_Products1_idx` ON `api-restful-shop-diagram-db`.`Tickets` (`Products_idproducts` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`TypeDocument`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`TypeDocument` (
  `idtypedocument` INT NOT NULL,
  `nameTD` ENUM('Cédula', 'Pasaporte') NULL,
  `UsersDetails_idusersdetails` INT NOT NULL,
  PRIMARY KEY (`idtypedocument`, `UsersDetails_idusersdetails`));

CREATE INDEX `fk_TypeDocument_UsersDetails1_idx` ON `api-restful-shop-diagram-db`.`TypeDocument` (`UsersDetails_idusersdetails` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`Users` (
  `idusers` VARCHAR(45) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `roles` ENUM('user', 'vendedor', 'admin') NOT NULL,
  `idusersdetails` INT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UsersDetails_idusersdetails` INT NOT NULL,
  PRIMARY KEY (`idusers`, `UsersDetails_idusersdetails`));

CREATE INDEX `fk_Users_UsersDetails_idx` ON `api-restful-shop-diagram-db`.`Users` (`UsersDetails_idusersdetails` ASC);


-- -----------------------------------------------------
-- Table `api-restful-shop-diagram-db`.`UsersDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-restful-shop-diagram-db`.`UsersDetails` (
  `idusersdetails` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(32) NOT NULL,
  `secondname` VARCHAR(32) NULL,
  `lastname` VARCHAR(32) NOT NULL,
  `secondlastname` VARCHAR(32) NULL,
  `document` INT(8) NOT NULL,
  PRIMARY KEY (`idusersdetails`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
